[default]

[default.web]
port = 8000
host = "127.0.0.1"
log_level = "info"
reload = true
api_version = "v1"
api_path = "@format /api/{this.web.api_version}"
show_error_details = true
is_production = false

[default.web.logs]
ignore_loggers = [""]
logging_level = "DEBUG"

[default.web.docs]
path = "@format {this.web.api_path}/docs"
json_spec_path = "@format {this.web.api_path}/openapi.json"
yaml_spec_path = "@format {this.web.api_path}/openapi.yaml"
title = "Simple customer-friendly API"
version = "0.1 beta"

[default.db]
user = "postgres"
host = "localhost"
password = "postgres"
database = "clean_architecture_db"
connection_uri = "@format postgresql+asyncpg://{this.db.user}:{this.db.password}@{this.db.host}/{this.db.database}?prepared_statement_cache_size=500"

[default.web.auth]
secret_key = "23368667db5961f70f66a345bd9a01b3072535d8facfd651af236cfd7124dcc6"
algorithm = "HS256"